config/routes.rb
Dexx::Application.routes.draw do
  resources :cards do
    collection do
      put "set"
      put "get"
      post "query"
    end
  end

  resources :templates do
    collection do
      put "add_property"
      put "delete_property"
      put "update_property"
    end
  end

  

end

app/views/templates/_form.html.erb
<%= form_for(@template) do |f| %>
  <% if @template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@template.errors.count, "error") %> prohibited this template from being saved:</h2>

      <ul>
      <% @template.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<hr/>

<%= form_for @template, url:template_add_property_path(@template.id), method:"get" do |f| %>
  <%= f.submit ("ADD") %>
<% end %>

app/views/templates/edit.html.erb
<h1>Editing template</h1>

<%= render 'form' %>

<%= link_to 'Show', @template %> |
<%= link_to 'Back', templates_path %>

app/views/templates/index.html.erb
<h1>Listing templates</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Packed properties</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @templates.each do |template| %>
      <tr>
        <td><%= template.name %></td>
        <td><%= template.properties %></td>
        <td><%= link_to 'Show', template %></td>
        <td><%= link_to 'Edit', edit_template_path(template) %></td>
        <td><%= link_to 'Destroy', template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Template', new_template_path %>

app/views/templates/new.html.erb
<h1>New template</h1>

<%= render 'form' %>

<%= link_to 'Back', templates_path %>

app/views/templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @template.name %>
</p>

<p>
  <strong>Packed properties:</strong>
  <%= @template.properties %>
</p>

<%= link_to 'Edit', edit_template_path(@template) %> |
<%= link_to 'Back', templates_path %>